### ISSUE TITLE
organization现在暂时采用了这个名字，如果有任何关于名字或头像的想法都依然可以在这里讨论

### ISSUE THREAD

**Issue by cnwangjie** [curdbin/introduction#1]
现在的名字是我随便搞的，然而我们可以搞一个更有牌面一点的名字:joy:，最好还能有dalao设计一个好看的头像
大家有什么想法都可以提出来啊！

**Comment by ylink-lfs** [comment]
"CurdBin" or "curd_bin"
含义：curd这里指提交上去的代码（有点自嘲），bin就是桶或者箱，表示存放大家写的小玩意的地方啊（顺带一提，这个名字在GitHub上还没有重名的）

**Comment by tmsshikun** [comment]
geek myth. 可以到http://www.fantasynamegenerators.com/这个网站找找酷一点的名词,组合一下

**Comment by seekun** [comment]
geek myth. 可以到这个网站找找名词,组合一下.
http://www.fantasynamegenerators.com/hacker-names.php#.WweUAlOFNTY

**Comment by hoochanlon** [comment]
怎么感觉组织的头像有些丑.. 微软的mssql图标不错
