### ISSUE TITLE
gitter / issues subscribe (交流的地方)

### ISSUE THREAD

**Issue by cnwangjie** [curdbin/introduction#10]
curdbin 目前还没有一个专门的讨论一些"正事"的地方,因为最早来源于学校的q群.但是既然建了org就希望大家可以围绕开源的主题进行一些讨论.现在唯一的讨论的地方就是q群,而(我对)q群的定位和设想从来就不是讨论正事的地方~~q群就是拿来水的~~,所以现在提出两个提案.

### issue

采用这个repo的issues作为讨论的地方,其实这种留言的形式的(非即使)的讨论在我心中会更加的高校.但是考虑到时效性的问题,需要大家都watch这个repo.这个是一件略微麻烦的事情

(对于上面提到的这个问题还有两个提案: 1. 自动邀请,oauth登录,并自动watch这个repo 2. 用 qq bot 吧issue同步到群里)

### gitter

之前考虑过建微信群.相对于建一个微信群,gitter更加方便(公开),而且不需要邀请所有人加入,大家都可以主动加入,并且也与org更加联动

**Comment by ylink-lfs** [comment]
自己倾向建一个gitter群，然后在qq群发一个关于gitter群的公告，有兴趣或有需求的人进

**Comment by cnwangjie** [comment]
@ylink-lfs 先这样吧,你来执行一下吧

**Comment by cnwangjie** [comment]
@ylink-lfs 可否在README中留一个gitter的链接. 另外是否有兴趣做一个invitation page?

**Comment by ylink-lfs** [comment]
README里留了gitter的链接。invitation page是做一个网页？那还是问问梅世琪吧，网页这块我不太会。

**Comment by loremwalker** [comment]
怎么感觉组织的头像有些丑..
