### ISSUE TITLE
计划做一个成员列表页

### ISSUE THREAD

**Issue by cnwangjie** [curdbin/introduction#2]
之前看到过很多组织都有成员列表页，可以方便大家互相认识。
本来想找一个链接的，可是不知道为什么找了半天也没找到。。。之前明明看到过很多的

大致就是一个页面有成员的头像（也可以没有），然后一行简短的介绍，然后再带上一个博客链接或者想分享的社交媒体链接。

我们可以弄一个单页，也可以用一个md文档。之后每个成员可以各自通过pr来把自己的链接和介绍放上。

@loliMay 你愿不愿意来弄一下呀？

**Comment by shiqimei** [comment]
OK
