### ISSUE TITLE
fork sync pr bot

### ISSUE THREAD

**Issue by cnwangjie** [curdbin/introduction#8]
~~一个长期以来的想法~~

fork的repo现在没有办法自动追随upstream,所以同学们点进我们fork的一些repo通常是落后的版本.

受到之前看到的依赖版本自动更新的PR bot的启发,打算做一个同步upstream的PR bot.监视upstream repo,如果设定的某一branch (通常是默认的branch) 如果有新的commit,则bot发起一个PR,将upstream合并到fork repo

reference:

 - [renovate](https://github.com/apps/renovate)
 - [github api](https://developer.github.com/v3/)

@loliMay 对此有什么设想可以在这里提一下,有空的话可以试着做一下

**Comment by shiqimei** [comment]
支持, 建议单独开个仓库造个轮子

**Comment by cnwangjie** [comment]
今天份摸鱼:
发现了一个很方便的东西https://github.com/probot/probot
再配合上https://github.com/octokit 感觉就可以很容易的做一个bot啦
我还抢注了一个感觉不错的名字https://github.com/apps/forkeeper
之后把转到org来就算是有拿得出手的项目啦:joy:

**Comment by cnwangjie** [comment]
@loliMay 惊了,就在我研究的时候突然发现了一个现成的.. https://github.com/backstrokeapp/server 试了一下居然能用

reference: https://github.com/curdbin/Student-resources/pull/1
